# Generated by Django 3.0.4 on 2020-05-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200420_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='teachers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Teaches'),
        ),
    ]
