# Generated by Django 3.0.4 on 2020-05-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Teaches'),
        ),
    ]
