# Generated by Django 3.0.4 on 2020-05-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200508_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_from_default',
            field=models.BooleanField(default=True),
        ),
    ]
