# Generated by Django 3.0.4 on 2020-05-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_is_from_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='teachers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Teaches'),
        ),
    ]
